spring:
  application:
    name: EmailServer
  mail:
    host: smtp.gmail.com
    port: 587
    username: eaairlinereservation@gmail.com
    password: cs544project
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
mail:
  smtp:
    debug: true
server:
  port:
    8081
