spring:
  application:
    name: EAProjectARS
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=ea_course;
    username: abditufa
    password: P@ss4%db%
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximumPoolSize: 10
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2008Dialect
  security:
    user:
      name: service-user
      password: 3b99fef5-8b7d-4984-a3d6-124c26914ed7
logging:
  file:
    name: /Coding/Logging/${spring.application.name}/log